######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "D:/Study/first/example/project_6/project_6.srcs/sources_1/edk/module_1"
if { [xload new module_1.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo ZC702

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
